### ISSUE TITLE
Can you provide the source code？

### ISSUE THREAD

**Issue by mrwen-hard** [zahrabsh74/YOLOMonodepth#1]
Dear author，Thank you so much for sharing，Can you provide the source code？

**Comment by zahrabsh74** [comment]
sorry for the late response. I will provide it as soon as possible

**Comment by mrwen-hard** [comment]
Thank you for the code.I have a question. Can this code display the depth information obtained by Monodepth together with the detection information of Yolo in the annotation box?

**Comment by zahrabsh74** [comment]
You're welcome. Yes, in yolodepth.py (Line 198-201) you can see the depth information obtained by Monodepth and the detection bounding-box of Yolo are both displayed in colormapped image:
```
            label='D=%scm' % (math.floor(center_point_distance))
            colormapped_im = (mapper.to_rgba(disp_resized_np)[:, :, :3] * 255).astype(np.uint8)
            cv2.rectangle(colormapped_im, c1, c2, [0, 0 ,0],2)
            cv2.putText(colormapped_im, label, (c1[0]+15, c1[1] - 2),cv2.FONT_HERSHEY_SIMPLEX,0.5, [0, 0 ,0], thickness=1, lineType=cv2.LINE_AA)
            im = pil.fromarray(colormapped_im)
```

**Comment by mrwen-hard** [comment]
Ok thanks for your reply, I will try it.
